#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.local/bin
  $HOME/.cargo/bin
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

###
# Modifications by Tynan
###

# Set up modifications for Python interactive shell.
if [[ -e "$HOME/.pystartup" ]]; then
  export PYTHONSTARTUP="$HOME/.pystartup"
fi

# Load any other potential modifications to the shell.
if [[ -e "$HOME/.zshext" ]]; then
  source "$HOME/.zshext"
fi

# Add local directory for zsh completion files.
fpath=(
  $fpath
  $HOME/.zfunc
)

# If fzf is installed by git, load it.
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# On some systems (mostly Linux, where fd already exists), fd is installed as fdfind. Create an alias for that.
if command -v fdfind > /dev/null 2>&1 ; then
  alias fd=fdfind
fi
